name: tests

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-linux-macos:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[testing]"
          : # pip install pytest nbmake
      - name: Run test
        run: |
          : # we were also testing the jupyter notebooks with the command below
          : # but some recent update broke this and we get "No such file or directory: 'latex'"
          : # so for now we don't test notebooks
          : # original command "pytest --nbmake ."
          pytest .

  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install ".[testing]"
          : # pip install pytest nbmake
      - name: Run test
        shell: bash -l {0}
        run: |
          : # we were also testing the jupyter notebooks with the command below
          : # but some recent update broke this and we get "No such file or directory: 'latex'"
          : # so for now we don't test notebooks
          : # original command "pytest --nbmake ."
          pytest .

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[testing]"
      - name: Tests
        run: |
          export NUMBA_DISABLE_JIT=1
          pytest --cov dreimac
      - name: Upload coverage results
        run: |
          bash <(curl -s https://codecov.io/bash)
